### ISSUE TITLE
Errore Sketch aes.hpp e ArduinoJson.h not found

### ISSUE THREAD

**Issue by geniomatto** [acortelyou/ArduinoTuya#2]
Salve a tutti... ho un problema con questa libreria. Alla compilazione dello sketch mi da questo errore:

/Users/Marco/Documents/Arduino/libraries/ArduinoTuya/src/ArduinoTuya.h:59:19: fatal error: aes.hpp: No such file or directory
 #include <aes.hpp>

/Users/Marco/Documents/Arduino/libraries/ArduinoTuya/src/ArduinoTuya.h:63:19: fatal error: ArduinoJson.h: No such file or directory
 #include <ArduinoJson.h>

Sapreste aiutarmi a risolvere?
Grazie

**Comment by WAT05** [comment]
Hi @geniomatto , 
I don't speak italian but I think I have the same issue here... Did you manage to fix it ? Or did you find another solution for your project ? 

@acortelyou hi, would you know a fix for it ?

Please let me know, any help would be great ! Thanks

Tanguy

**Comment by georgehunn** [comment]
Hi @WAT05, @geniomatto,

same issue aes.hpp not found. Any solution / workaround?

**Comment by acortelyou** [comment]
This library relies on the tiny-AES-c and ArduinoJson libraries.

Since creating this project Arduino IDE has added support for libraries naming dependencies so I will add them to the manifest.

I no longer run the original firmware on my Tuya devices so please consider this repo as reference material, if you run into any issues I will accept PRs but no further development is planned.

See https://tasmota.github.io/docs/Tuya-Convert/ for more information.

**Comment by acortelyou** [comment]
https://github.com/acortelyou/ArduinoTuya/commit/842e1e6aebce0465fbd15ee105a5593c458f1c06
